var MediatRDomainEventDispatcher_8cs =
[
    [ "TaskManagement.Infrastructure.EventDispatching.MediatRDomainEventDispatcher", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1MediatRDomainEventDispatcher.html", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1MediatRDomainEventDispatcher" ],
    [ "TaskManagement.Infrastructure.EventDispatching.DomainEventWrapper< T >", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1DomainEventWrapper.html", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1DomainEventWrapper" ],
    [ "TaskManagement.Infrastructure.EventDispatching.TaskCompletedNotificationHandler", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1TaskCompletedNotificationHandler.html", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1TaskCompletedNotificationHandler" ]
];