var namespaceTaskManagement_1_1Infrastructure_1_1EventDispatching =
[
    [ "DomainEventWrapper", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1DomainEventWrapper.html", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1DomainEventWrapper" ],
    [ "MediatRDomainEventDispatcher", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1MediatRDomainEventDispatcher.html", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1MediatRDomainEventDispatcher" ],
    [ "TaskCompletedNotificationHandler", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1TaskCompletedNotificationHandler.html", "classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1TaskCompletedNotificationHandler" ]
];