var searchData=
[
  ['id_0',['id',['../classTaskManagement_1_1Domain_1_1Events_1_1DomainEvent.html#ab3518119684c7bac4a11bad1edfabd23',1,'TaskManagement.Domain.Events.DomainEvent.Id'],['../classTaskManagement_1_1Domain_1_1Entities_1_1TaskItem.html#ae322353612c3de26fdc0cd39f0c4b893',1,'TaskManagement.Domain.Entities.TaskItem.Id'],['../classTaskManagement_1_1Application_1_1Queries_1_1GetTaskById_1_1TaskDto.html#ad3afe6f743e332de9e0d2e096d76f585',1,'TaskManagement.Application.Queries.GetTaskById.TaskDto.Id']]],
  ['idomaineventdispatcher_1',['IDomainEventDispatcher',['../interfaceTaskManagement_1_1Application_1_1Interfaces_1_1IDomainEventDispatcher.html',1,'TaskManagement::Application::Interfaces']]],
  ['idomaineventdispatcher_2ecs_2',['IDomainEventDispatcher.cs',['../IDomainEventDispatcher_8cs.html',1,'']]],
  ['iemailservice_3',['IEmailService',['../interfaceTaskManagement_1_1Application_1_1Interfaces_1_1IEmailService.html',1,'TaskManagement::Application::Interfaces']]],
  ['iemailservice_2ecs_4',['IEmailService.cs',['../IEmailService_8cs.html',1,'']]],
  ['ientitytypeconfiguration_5',['IEntityTypeConfiguration',['../classIEntityTypeConfiguration.html',1,'']]],
  ['ii_6',['Análisis y diseño de aplicaciones II',['../md__2home_2runner_2work_2ANDIS__CleanArchitecture__Demo_2ANDIS__CleanArchitecture__Demo_2README.html#autotoc_md19',1,'']]],
  ['implementación_20de_20la_20arquitectura_7',['Implementación de la arquitectura',['../index.html#autotoc_md5',1,'']]],
  ['index_2emd_8',['index.md',['../index_8md.html',1,'']]],
  ['infraestructura_9',['3. Capa de infraestructura',['../index.html#autotoc_md13',1,'']]],
  ['ingeniería_20y_20tecnologías_10',['Facultad de Ingeniería y Tecnologías',['../md__2home_2runner_2work_2ANDIS__CleanArchitecture__Demo_2ANDIS__CleanArchitecture__Demo_2README.html#autotoc_md18',1,'']]],
  ['inotification_11',['INotification',['../classINotification.html',1,'']]],
  ['inotificationhandler_12',['INotificationHandler',['../classINotificationHandler.html',1,'']]],
  ['inprogress_13',['InProgress',['../namespaceTaskManagement_1_1Domain_1_1Entities.html#ad04bec97d0816e405027fbfc8e088251a12d868c18cb29bf58f02b504be9033fd',1,'TaskManagement::Domain::Entities']]],
  ['interfaces_20definidos_20en_20cada_20capa_14',['Resumen de clases e interfaces definidos en cada capa',['../index.html#autotoc_md10',1,'']]],
  ['interfaz_15',['4. Capa de interfaz',['../index.html#autotoc_md14',1,'']]],
  ['introducción_16',['Introducción',['../index.html',1,'']]],
  ['ipipelinebehavior_17',['IPipelineBehavior',['../classIPipelineBehavior.html',1,'']]],
  ['irequesthandler_18',['IRequestHandler',['../classIRequestHandler.html',1,'']]],
  ['isfailure_19',['IsFailure',['../classTaskManagement_1_1Domain_1_1Common_1_1Result.html#a395cffa1a3db113c334a5e27632ac8f2',1,'TaskManagement::Domain::Common::Result']]],
  ['issuccess_20',['IsSuccess',['../classTaskManagement_1_1Domain_1_1Common_1_1Result.html#a4965d2246e261d3e8ef318c406363810',1,'TaskManagement::Domain::Common::Result']]],
  ['itaskreadrepository_21',['ITaskReadRepository',['../interfaceTaskManagement_1_1Application_1_1Interfaces_1_1ITaskReadRepository.html',1,'TaskManagement::Application::Interfaces']]],
  ['itaskreadrepository_2ecs_22',['ITaskReadRepository.cs',['../ITaskReadRepository_8cs.html',1,'']]],
  ['itaskrepository_23',['ITaskRepository',['../interfaceTaskManagement_1_1Application_1_1Interfaces_1_1ITaskRepository.html',1,'TaskManagement::Application::Interfaces']]],
  ['itaskrepository_2ecs_24',['ITaskRepository.cs',['../ITaskRepository_8cs.html',1,'']]],
  ['items_25',['Items',['../classTaskManagement_1_1Application_1_1Common_1_1PagedResult.html#a51012f91a04ff4910e7e7283ab530e68',1,'TaskManagement::Application::Common::PagedResult']]],
  ['iunitofwork_26',['IUnitOfWork',['../interfaceTaskManagement_1_1Application_1_1Interfaces_1_1IUnitOfWork.html',1,'TaskManagement::Application::Interfaces']]],
  ['iunitofwork_2ecs_27',['IUnitOfWork.cs',['../IUnitOfWork_8cs.html',1,'']]]
];
