var searchData=
[
  ['dbcontext_0',['DbContext',['../classDbContext.html',1,'']]],
  ['de_20aplicación_1',['2. Capa de aplicación',['../index.html#autotoc_md12',1,'']]],
  ['de_20aplicaciones_20ii_2',['Análisis y diseño de aplicaciones II',['..//Users/fmachado/Repos/ANDIS_CleanArchitecture_Demo/README.md#autotoc_md19',1,'']]],
  ['de_20código_3',['Diagrama C4 de código',['../index.html#autotoc_md4',1,'']]],
  ['de_20clases_20e_20interfaces_20definidos_20en_20cada_20capa_4',['Resumen de clases e interfaces definidos en cada capa',['../index.html#autotoc_md10',1,'']]],
  ['de_20clean_20architecture_5',['de Clean Architecture',['../index.html#autotoc_md16',1,'Beneficios de Clean Architecture'],['..//Users/fmachado/Repos/ANDIS_CleanArchitecture_Demo/README.md#autotoc_md20',1,'Demo de Clean Architecture']]],
  ['de_20componentes_6',['Diagrama C4 de componentes',['../index.html#autotoc_md3',1,'']]],
  ['de_20contenedores_7',['Diagrama C4 de contenedores',['../index.html#autotoc_md2',1,'']]],
  ['de_20dominio_8',['1. Capa de dominio',['../index.html#autotoc_md11',1,'']]],
  ['de_20infraestructura_9',['3. Capa de infraestructura',['../index.html#autotoc_md13',1,'']]],
  ['de_20ingeniería_20y_20tecnologías_10',['Facultad de Ingeniería y Tecnologías',['..//Users/fmachado/Repos/ANDIS_CleanArchitecture_Demo/README.md#autotoc_md18',1,'']]],
  ['de_20interfaz_11',['4. Capa de interfaz',['../index.html#autotoc_md14',1,'']]],
  ['de_20la_20arquitectura_12',['Implementación de la arquitectura',['../index.html#autotoc_md5',1,'']]],
  ['de_20sistema_20de_20software_13',['Diagrama C4 de sistema de software',['../index.html#autotoc_md1',1,'']]],
  ['de_20software_14',['Diagrama C4 de sistema de software',['../index.html#autotoc_md1',1,'']]],
  ['definidos_20en_20cada_20capa_15',['Resumen de clases e interfaces definidos en cada capa',['../index.html#autotoc_md10',1,'']]],
  ['del_20uruguay_16',['Universidad Católica del Uruguay',['..//Users/fmachado/Repos/ANDIS_CleanArchitecture_Demo/README.md#autotoc_md17',1,'']]],
  ['demo_20de_20clean_20architecture_17',['Demo de Clean Architecture',['..//Users/fmachado/Repos/ANDIS_CleanArchitecture_Demo/README.md#autotoc_md20',1,'']]],
  ['diagrama_20c4_20de_20código_18',['Diagrama C4 de código',['../index.html#autotoc_md4',1,'']]],
  ['diagrama_20c4_20de_20componentes_19',['Diagrama C4 de componentes',['../index.html#autotoc_md3',1,'']]],
  ['diagrama_20c4_20de_20contenedores_20',['Diagrama C4 de contenedores',['../index.html#autotoc_md2',1,'']]],
  ['diagrama_20c4_20de_20sistema_20de_20software_21',['Diagrama C4 de sistema de software',['../index.html#autotoc_md1',1,'']]],
  ['diseño_20de_20aplicaciones_20ii_22',['Análisis y diseño de aplicaciones II',['..//Users/fmachado/Repos/ANDIS_CleanArchitecture_Demo/README.md#autotoc_md19',1,'']]],
  ['domainevent_23',['DomainEvent',['../classTaskManagement_1_1Domain_1_1Events_1_1DomainEvent.html',1,'TaskManagement::Domain::Events']]],
  ['domaineventwrapper_2d1_2dg_24',['DomainEventWrapper-1-g',['../classTaskManagement_1_1Infrastructure_1_1EventDispatching_1_1DomainEventWrapper-1-g.html',1,'TaskManagement::Infrastructure::EventDispatching']]],
  ['domainexception_25',['DomainException',['../classTaskManagement_1_1Domain_1_1Exceptions_1_1DomainException.html',1,'TaskManagement::Domain::Exceptions']]],
  ['dominio_26',['1. Capa de dominio',['../index.html#autotoc_md11',1,'']]],
  ['drapper_27',['Drapper',['../index.html#autotoc_md9',1,'']]]
];
