#!/usr/bin/env python3
"""
Script to customize SVG diagrams generated by Doxygen.
Changes the background to transparent and sets custom colors (#0969DA for lines/text).
Color #0969DA in RGB: rgb(9, 105, 218)
"""

import os
import re
from pathlib import Path

def customize_svg(svg_file):
    """Modify SVG file to have transparent background and custom colors."""
    try:
        with open(svg_file, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Replace white background with transparent
        # Remove white polygon backgrounds
        content = re.sub(
            r'<polygon[^>]*fill="white"[^>]*>',
            '<polygon fill="none" stroke="transparent">',
            content
        )
        
        # Replace white rect backgrounds  
        content = re.sub(
            r'<rect[^>]*fill="white"[^>]*/>',
            '',
            content
        )
        
        # Replace default Graphviz colors with #0969DA
        # Replace the light blue default (#63b8ff) with our custom blue
        content = re.sub(
            r'stroke="#63b8ff"',
            'stroke="#0969DA"',
            content
        )
        
        content = re.sub(
            r'fill="#63b8ff"',
            'fill="#0969DA"',
            content
        )
        
        # Also handle black if it exists
        content = re.sub(
            r'stroke="black"',
            'stroke="#0969DA"',
            content
        )
        
        # Change text colors - replace black text color
        content = re.sub(
            r'fill="black"',
            'fill="#0969DA"',
            content
        )
        
        # Handle color attribute
        content = re.sub(
            r'color="black"',
            'color="#0969DA"',
            content
        )
        
        with open(svg_file, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return True
    except Exception as e:
        print(f"Error processing {svg_file}: {e}")
        return False

def main():
    """Process all SVG files in the html directory."""
    html_dir = Path('html')
    
    if not html_dir.exists():
        print(f"Error: {html_dir} directory not found")
        return
    
    # Look for all .svg files that are diagram files
    svg_files = list(html_dir.glob('*graph.svg'))
    print(f"Found {len(svg_files)} SVG graph files to process")
    
    success_count = 0
    for svg_file in svg_files:
        if customize_svg(svg_file):
            success_count += 1
            print(f"✓ {svg_file.name}")
        else:
            print(f"✗ {svg_file.name}")
    
    print(f"\nProcessed {success_count}/{len(svg_files)} files successfully")

if __name__ == '__main__':
    main()
